# Generated by Django 3.1 on 2021-04-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
